### ISSUE TITLE
I got CORS policy error using vue-img-watermark plugin

### ISSUE THREAD

**Issue by PetroGromovo** [serializedowen/vue-img-watermark#2]
Hello,
In my @vue/cli 4.0.5 app with Laravel 7 Backend API as data source I want to add watermark to my image “on fly”
I found this https://www.vuescript.com/custom-watermarks/ 
example and try to use it but I got error in console : 

```
Access to image at 'http://local-ctasks-api.com/storage/tasks/-task-3/design-new-task.png' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
design-new-task.png:1 GET http://local-ctasks-api.com/storage/tasks/-task-3/design-new-task.png net::ERR_FAILED

```
where http://local-ctasks-api.com/ is hosting of Laravel Backend API on my local ubuntu apache. 
To escape CORS error I use  "barryvdh/laravel-cors": "^1.0.5" on Laravel Backend API side 
and it works for me.

I do in my vue file :

```
<img
    v-if="taskHasImage(taskRow)"
    class="pull-left m-1 p-1 task_image"
    :src="taskRow.filenameData.image_url"
    alt="Task Image"
    v-watermark="watermarkOptions"
/>

...

<script>
    import {bus} from '../../../src/main'
    import axios from 'axios'
    ...
    import plugin from '@serializedowen/vue-img-watermark'
    Vue.use(plugin)
    

        data: function () {
            return {
               ... 

                watermarkOptions : {  // eslint-disable-line
                    // "bottomleft", "bottomright", "topleft", "topright", "center", "fill"
                    mode: "bottomright",
                    textBaseline: "middle",
                    font: "15px Arial",
                    fillStyle: "white",
                    content: "@vuescript.com",
                    rotate: 30
                }, // https://www.vuescript.com/custom-watermarks/

```

Reading description at https://github.com/serializedowen/vue-img-watermark :
I see mentioned of setScopedConfig and registerCustomStrategy using but I did not find examples of 
these methods using. Can it be that I have CORS errors because of misconfiguring of these methods?

Please, give full code of your demo example.

How to fix my error ?

Thanks!

**Comment by serializedowen** [comment]
example is right in repo, just install dependencies then `npm run demo`,
I'll dig into your issue while you explore the example

**Comment by serializedowen** [comment]
If you are serving static assets from a different origin, you'll need `Access-Control-Allow-Origin` as you have mention and fixed, there's nothing to do with front-end misconfiguration. 

You can find documentation for `registerCustomStrategy` and `setScopedConfig` in readme and trying out in example.

**Comment by PetroGromovo** [comment]
I tried to upload examples but got message : Uploads are disabled.
File uploads require push access to this repository.

Can I upload it and install? Actually I do not see any vue files there...
Please, check.

**Comment by serializedowen** [comment]
You mean to provide a reproduction to your issue? You can fork the repo and modify it over there. Oh but yeah, for simplicity i wrote the example in .js, but it's in vue syntax.

**Comment by serializedowen** [comment]
If you aren't experiencing any problem & blocks. I'm gonna go ahead and close this issue.
